
server:
  port:8080

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username : root
    password : cy123456
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    show-sql : true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace